(load "./nl-unittest.lsp")
(load "vimhelp.lsp")

(define-test (test_vim-rules)
  (assert= "unchanged"   (vim-rules "unchanged"))
  (assert= "star"        (vim-rules "*"))
  (assert= "gstar"       (vim-rules "g*"))
  (assert= "[star"       (vim-rules "[*"))
  (assert= "]star"       (vim-rules "]*"))
  (assert= "g??"         (vim-rules "g??"))
  (assert= {/\\(\\)}     (vim-rules {/\\(\\)}))
  (assert= {\(\)}        (vim-rules {()}))
  (assert= {\[}          (vim-rules {[}))
  (assert= "\\[pattern]" (vim-rules "[pattern]"))
  (assert= {\\bar}       (vim-rules {\|}))
  (assert= {/\\%\\$}     (vim-rules {\\%$}))
  (assert= "\\\\{"       (vim-rules "\\{"))
  (assert= {\[:alpha:\]} (vim-rules {[:alpha:]}))
  (assert= {\\.}         (vim-rules {.}))
  (assert= {bar}         (vim-rules {|}))
  (assert= {quote}       (vim-rules {"}))
  (assert= {foo.*}       (vim-rules {foo*}))
  (assert= {foo.}        (vim-rules {foo?}))
  (assert= {~}           (vim-rules {~}))
  (assert= {ctrl-x}      (vim-rules {^x}))
  (assert= {x_ctrl-x}    (vim-rules {x^x}))
  (assert= {/\\bar}      (vim-rules {/\|}))
  (assert= {c_CTRL-\\_e} (vim-rules {c_CTRL-\_e}))
  (assert= {CTRL-\\_}    (vim-rules {CTRL-\_}))
  (assert= "'option'"    (vim-rules "'option'."))
  (assert= "command"     (vim-rules "`command`"))
  )

(define (best-tag tag)
  (first (first (ordered-tags tag))))

(define-test (test_best-match)
  (assert= "clipboard" (best-tag "clipboard"))
  (assert= "X"         (best-tag "x"))
  (assert= ":X"        (best-tag ":x"))
  (assert= "CTRL-X"    (best-tag "^x"))
  (assert= "/\\+"      (best-tag "\\+"))
  (assert= "+"         (best-tag "+"))
  )

(define-test (test_url)
  (assert= "http://vimhelp.appspot.com/change.txt.html#CTRL%2DX" (vimhelp "^x"))
  (assert= "http://vimhelp.appspot.com/undo.txt.html#%3Alater" (vimhelp "ate"))
  )

(UnitTest:run-all MAIN)

(exit 0)
